### ISSUE TITLE
lintr issues in ./Analysis.Rmd need to be fixed

### ISSUE THREAD

**Issue by naupaka** [mfhamir/apple_mobility_2021#10]
**Linting errors in the Rmd file(s)**
```
Analysis.Rmd:110:1: style: Lines should not be more than 80 characters.
# create a timeseries plot of the mean relative driving mobility across the state
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Analysis.Rmd:166:1: style: Trailing blank lines are superfluous.

^
```

**Comment by mfhamir** [comment]
5a83e38b7e8ee2125021ba8e16a07082f6c89e27

57a4ee3060b340f3574d723de96c8b739e04ddfd

I had checked and found a lot of lintr errors, so I fixed them and committed all at the same time, will share these links with all lintr issues. Thank you

**Comment by sarah-gao** [comment]
All the lintr errors look fixed now, thanks!
