### ISSUE TITLE
Helper prompts are redundant

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#14]
The text for these helper prompts are redundant and need to specify the correct accepted arguments.
https://github.com/mfhamir/apple_mobility_2021/blob/8c6aff5cc32b1a17caf6faf5c84436b87dbb4653/run_analyze_covid_pipeline.sh#L16

**Comment by mfhamir** [comment]
1a6df5476cbdac649c2755f0c9064794a39c0e7f - fixed the prompt to state the name

**Comment by sarah-gao** [comment]
Looks good!
