### ISSUE TITLE
Capitalize section header

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#16]
https://github.com/mfhamir/apple_mobility_2021/blob/ac9aa992dacf56020aef6f69f1d89f60984d1670/Analysis.Rmd#L84

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/0c10a9923b3016515e1b25332ad39eb6bebd2b27

I also fixed this error and committed it together when I updated readme and the 02 script

**Comment by sarah-gao** [comment]
@mfhamir Doesn't look like it's fixed in that commit?

**Comment by sarah-gao** [comment]
Ok I see that it was fixed in `parameterize-rmd`. Please try to make sure the commits you link to are the right ones.
