### ISSUE TITLE
02 script missing

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#17]
Is this the 02 script to tally up cities and counties? If so, it should be properly labelled. If not, it needs to be correctly organized, perhaps filed in archived or something.

https://github.com/mfhamir/apple_mobility_2021/blob/ac9aa992dacf56020aef6f69f1d89f60984d1670/code/countupcitiessource.R

**Comment by mfhamir** [comment]
Hi Sarah, no this is not my 02 script. my 02 is in functions. This was a code that I no longer use I just did not want to delete it because of previous issues encountered.

**Comment by mfhamir** [comment]
I will try move it to archived

**Comment by mfhamir** [comment]
Could I simply move it from the files tab in R studio or could that end up being problematic?

**Comment by sarah-gao** [comment]
@mfhamir Only functions should be in the functions folder whereas the 02 script is a script that calls that function but is not a function in and of itself. Please reorganize your files so that everything is in the proper place. You can do that in RStudio or in your normal file navigator (eg in Finder on MacOS) or through the bash terminal.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/0c10a9923b3016515e1b25332ad39eb6bebd2b27

- I made the respective updates so the README file has been updated, I have also put those extra files we discussed into the archived functions folder

**Comment by sarah-gao** [comment]
@mfhamir Looks like your 02 script still isn't in your code folder?

**Comment by mfhamir** [comment]
Hi Sarah,

It is in there and I fixed those issues. It seems that I pushed not to main
but to paramertize. But I did make those changes and my code has the 02 in
it. Which I retitled? Is that not visible from your your end?

Best,
Muhammed

**Comment by sarah-gao** [comment]
Ah yes I found it now, not sure if I was looking at the wrong branch or if that push just came through. Closing this issue now, thanks
