### ISSUE TITLE
Inaccurate description

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#19]
Take another pass at your script header. Revisit the assignment and think about what you're trying to do with this script and what's happening with each step.

https://github.com/mfhamir/apple_mobility_2021/blob/9e12bff7e04dcfb895f9fa0953b7bf59d1de867c/code/process_sequences.sh#L1

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/33f5bb2637cbf783ba480c731b69f2db1f8f4c29

**Comment by sarah-gao** [comment]
This is much better, thanks!
