### ISSUE TITLE
Typo in helper prompt

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#20]
Should be "supply one argument".

https://github.com/mfhamir/apple_mobility_2021/blob/9e12bff7e04dcfb895f9fa0953b7bf59d1de867c/code/process_sequences.sh#L12

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/33f5bb2637cbf783ba480c731b69f2db1f8f4c29

**Comment by sarah-gao** [comment]
I would recommend just showing the entire output with just one argument, without requiring the extra "ALL" argument as a more elegant solution. But this commit does remove the typo so closing for now.
