### ISSUE TITLE
Need context for this output

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#21]
The user needs some context to understand what this output is.

https://github.com/mfhamir/apple_mobility_2021/blob/9e12bff7e04dcfb895f9fa0953b7bf59d1de867c/code/process_sequences.sh#L24

**Comment by mfhamir** [comment]
Hi Sarah, I tried putting all the prompt at the top because it was giving errors in running it, I will rearrange them correctly.


https://github.com/mfhamir/apple_mobility_2021/commit/33f5bb2637cbf783ba480c731b69f2db1f8f4c29

**Comment by sarah-gao** [comment]
@mfhamir There's still no context for your output if you only have one argument. This is why I think it'd be easier to just show everything without requiring two arguments, i.e. omitting the "ALL" argument requirement. You still need to include some `echo` statement that gives the user context if they only do one argument, similarly to how you included context with the two arguments `if` block.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/4dfec8e9c36600ed6b87b148365a53d8a7c1ef99

Please let me know if this is better

**Comment by sarah-gao** [comment]
Yes, that works, thanks!
