### ISSUE TITLE
Shellcheck error

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#22]
```
In process_sequences.sh line 1:
# This is the pathway to compress the file into a command line argument
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
```

https://github.com/mfhamir/apple_mobility_2021/blob/2e63e6c1f1656100bf4569c62c1977cd11c4e8cc/code/process_sequences.sh#L1

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/33f5bb2637cbf783ba480c731b69f2db1f8f4c29

**Comment by sarah-gao** [comment]
Looks good now, thanks!
