### ISSUE TITLE
Typos in helper prompts

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#23]
https://github.com/mfhamir/apple_mobility_2021/blob/33f5bb2637cbf783ba480c731b69f2db1f8f4c29/code/process_sequences.sh#L15

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/4dfec8e9c36600ed6b87b148365a53d8a7c1ef99

**Comment by sarah-gao** [comment]
Much better! 👍
