### ISSUE TITLE
Used functions should be in functions folder

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#25]
If you're actively using this function, you should probably put it in the `functions` folder, not in `archived`

https://github.com/mfhamir/apple_mobility_2021/blob/c390c87beef07a7f31c4fe3c5aef254525b2acc7/code/02_countup_cities_source.R#L10

**Comment by sarah-gao** [comment]
@mfhamir It looks like you have two copies of this function...one in the code/functions folder and one in the code/ folder. Please take another pass at cleaning up this folder as it looks like your 02 script is missing from your code/ folder as well. It looks like it's erroneously in the code/functions folder.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/1b8641efa6e69806586acdfcaf4a1bf04028adf8

I think this is much better. I had an issue with my branches so when I had committed it did not fully include changes I made, which is why it did not show up well when you opened them

**Comment by naupaka** [comment]
That commit ID seems not to refer to this problem? It's just the addition of a comment.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/f86928e46a89d12dfc2648e2f1872ced64dd891e

**Comment by sarah-gao** [comment]
Resolved, thanks!
