### ISSUE TITLE
Typo in command prompt

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#27]
https://github.com/mfhamir/apple_mobility_2021/blob/4dfec8e9c36600ed6b87b148365a53d8a7c1ef99/code/process_sequences.sh#L15

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/b68b77287a207dec787c268214b68d87c633320f

**Comment by sarah-gao** [comment]
Fixed!
