### ISSUE TITLE
Else statement not necessary

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#29]
It appears that this else statement would only occur if the user inputted something that didn't match any of the conditions of the above `if` statements. So the error message to check the file for errors would not apply here. I think you have enough defensive checks to just remove this else statement entirely.

https://github.com/mfhamir/apple_mobility_2021/blob/4dfec8e9c36600ed6b87b148365a53d8a7c1ef99/code/process_sequences.sh#L37

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/d670616ee292c3db1839a2aa53c019a74aeef2d0

**Comment by sarah-gao** [comment]
Looks good!
