### ISSUE TITLE
Lintr warnings

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#32]
Several lintr warnings going on:

1: In readLines(filename) :
  incomplete final line found on 'code/countupcitiessource.R'
2: In readLines(filename) :
  incomplete final line found on 'code/functions/02_count_up_counties_cities.R'
3: In readLines(filename) :
  incomplete final line found on 'code/functions/convert_mobility_wide_to_long.R'
4: In readLines(filename) :
  incomplete final line found on 'code/functions/countupcitiessource.R'
5: In readLines(filename) :
  incomplete final line found on 'code/functions/subset_mobility_data_to_state.R'

I would highly recommend you change your RStudio settings so that it automatically adds the new line for you upon saving. (Also please run lintr prior to pushing / submitting to save on the back and forth lol)

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/1b8641efa6e69806586acdfcaf4a1bf04028adf8

lintr errors are fine and I cleaned things up a lot better

**Comment by naupaka** [comment]
This commit does not include any changes that address the issue. Perhaps you copied the wrong one?

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/f86928e46a89d12dfc2648e2f1872ced64dd891e

**Comment by sarah-gao** [comment]
Looks fixed, thanks!
