### ISSUE TITLE
Missing header info

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#33]
https://github.com/mfhamir/apple_mobility_2021/blob/acf19cf15b36495f12b6fc3abd54cb78e402eea6/code/functions/02_count_up_counties_cities.R#L1

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/f86928e46a89d12dfc2648e2f1872ced64dd891e

**Comment by sarah-gao** [comment]
Much better!
