### ISSUE TITLE
lintr issues in ./code/02_countup_cities_source.R need to be fixed

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#34]
**Linting errors in the R script ./code/02_countup_cities_source.R**
```
code/02_countup_cities_source.R:23:1: style: Trailing blank lines are superfluous.

^
```

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/dd06d2623b89d75d3506638df126c1dc18571038

**Comment by sarah-gao** [comment]
Fixed, thanks
