### ISSUE TITLE
Redundant code can be taken out

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#36]
These few lines in your script are redundant since you subset the same state in your for loop. You can take them out and keep the for loop that runs through the states to subset. That way, any other states you'd want to subset could be added to the for loop as well.

https://github.com/mfhamir/apple_mobility_2021/blob/e1a4b0705b1a61c46618baeb9b1afd60214dbe01/code/01_subset_data_to_a_state.R#L15

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/384989e1701691f84346f1060874a3c51a09eebc

**Comment by sarah-gao** [comment]
Hey @mfhamir there's still some redundant code here, now in lines 14-18.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/fcd09aea5c571c71a1cecdfb4b4c29e6589634dc

I renamed it as a test, because If I need to revisit it at some point that chunk gives an idea of what I should do, as it looks at one state. but the code works. I just labelled it as a test in the header so it should be fine

**Comment by sarah-gao** [comment]
@mfhamir You really shouldn't be leaving test code in your scripts either. If you really want to keep it, you could save this older version as a copy and then archive it while keeping the clean new version in your `code/` folder. But I think it's simple enough where it's not necessary to keep and could be easily rewritten if you ever needed to.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/7729e6bbfa941a703eacd2c57bb13c66c80e2f90

**Comment by sarah-gao** [comment]
👍
