### ISSUE TITLE
Duplicated output

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#37]
Looks like there's both the `analyze-sequences.txt` and `sequence_summary.txt` in your `output/` folder that are very similar.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/885fbf0ea534339fd22a8639aceaad5d743b4cb3

**Comment by sarah-gao** [comment]
Yay it's gone
