### ISSUE TITLE
Capitalize section header

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#38]
https://github.com/mfhamir/apple_mobility_2021/blob/dd06d2623b89d75d3506638df126c1dc18571038/Analysis.Rmd#L87

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/7fea23c9b977f80cbc2ced6b1333ea08a121cf8a

**Comment by sarah-gao** [comment]
Great, thanks for the fix!
