### ISSUE TITLE
Outdated make clean paths

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#39]
These are probably outdated, but they don't currently clean what you want when you run `make clean`

https://github.com/mfhamir/apple_mobility_2021/blob/dd06d2623b89d75d3506638df126c1dc18571038/Makefile#L24

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/4a69cdc8d9e170406a42336320e801a8e01bb207

**Comment by sarah-gao** [comment]
That did it, thanks!
