### ISSUE TITLE
Error running makefile

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#40]
```
Quitting from lines 163-185 (Analysis.Rmd) 
Error in log(x, base) : non-numeric argument to mathematical function
Calls: <Anonymous> ... <Anonymous> -> f -> lapply -> FUN -> f -> <Anonymous>

Execution halted
make: *** [Makefile:16: output/Analysis_.html] Error 1
```

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/fa73f0e9935b97719cc7a6ffeefddf28dc29982d

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/e71beb2798fd909d228561e4750f8c957489630a

this is just me committing the deleted seq summary that got deleted after I did makeclean

**Comment by sarah-gao** [comment]
@mfhamir I guess the latest commit does resolve the error, but you've taken out your sequences figure entirely. This is one of the major requirements for the assignment. Closing this issue and opening a new one for the missing plot #44
