### ISSUE TITLE
lintr issues in ./code/02_countup_cities_source.R need to be fixed

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#43]
**Linting errors in the R script ./code/02_countup_cities_source.R**
```
code/02_countup_cities_source.R:15:26: style: Commas should always have a space after.
the_state <- c("Alabama","Maryland", "Idaho", "Arizona", "Iowa")
                         ^
code/02_countup_cities_source.R:27:1: style: Trailing blank lines are superfluous.

^
```

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/70c8a2b45cb3f31d83d543fc0dafcc1bed0b1538

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/371ec85a5a6d561ccdf8415d8bfbc9ed419cadc4

This is the right commit

**Comment by sarah-gao** [comment]
Looks good now!
