### ISSUE TITLE
Missing sequences plot

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#44]
You had it in there before in your `Analysis.Rmd`, not sure why it's gone now?

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/c6b0def5c70df63e94a7c70b801e6d23fb772bcb

The plot is back

**Comment by sarah-gao** [comment]
Looks like it, closing!

("The plot is back" sounds like a great movie subtitle by the way)
