### ISSUE TITLE
Error running Analysis.Rmd

### ISSUE THREAD

**Issue by sarah-gao** [mfhamir/apple_mobility_2021#46]
```Error in log(x, base) : non-numeric argument to mathematical function```

This is the same error as #40 before, by the way. I don't think you ever fixed it, just took the entire plot out. Please take another look.

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/a7c9a5f369a0498d432730d150176663df2a9bdf

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/80304eb2bab2e585cbbdb6b25bded3c9cca765a7

**Comment by mfhamir** [comment]
https://github.com/mfhamir/apple_mobility_2021/commit/194c66961ebe4b40f35fc836359543a30e72bdcf

**Comment by sarah-gao** [comment]
Fixed now, hooray!
